-- Generated by scripts/hypr2lua.
-- Source: omarchy-oxocarbon-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgba(78a9ffee)", "rgba(3ddbd9ee)", "rgba(78a9ffee)" },
  angle = 45,
}
local inactiveBorderColor = "rgba(52525255)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 2,
    gaps_in = 4,
    gaps_out = 8,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    rounding = 0,
    dim_inactive = true,
    dim_strength = 0.15,
    fullscreen_opacity = 1.0,
    blur = {
      enabled = true,
      size = 5,
      passes = 3,
      noise = 0.02,
      contrast = 1.12,
      brightness = 0.86,
      vibrancy = 0.18,
      vibrancy_darkness = 0.72,
      ignore_opacity = true,
      new_optimizations = true,
      xray = false,
      popups = true,
      popups_ignorealpha = 0.60,
    },
    shadow = {
      enabled = true,
      range = 20,
      render_power = 3,
      color = "rgba(00000099)",
      color_inactive = "rgba(0000004d)",
      offset = "2 4",
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("carbonEase", { type = "bezier", points = { { 0.4, 0 }, { 0.2, 1 } } })

hl.animation({
  leaf = "borderangle",
  enabled = true,
  speed = 20,
  bezier = "carbonEase",
  style = "once",
})
hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 3,
  bezier = "carbonEase",
  style = "slide",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 3,
  bezier = "carbonEase",
  style = "slide",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 3,
  bezier = "carbonEase",
  style = "slide",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 3,
  bezier = "carbonEase",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 4,
  bezier = "carbonEase",
  style = "slide",
})

hl.window_rule({
  no_blur = true,
  match = {
    class = "^(walker)$",
  },
})
hl.window_rule({
  no_blur = true,
  match = {
    class = "^(swayosd)$",
  },
})
