# ========= Border =========
file_panel_border = '#525252'
sidebar_border = '#525252'
footer_border = '#525252'

# ========= Border Active =========
file_panel_border_active = '#78a9ff'
sidebar_border_active = '#78a9ff'
footer_border_active = '#78a9ff'
modal_border_active = '#78a9ff'

# ========= Background (bg) =========
full_screen_bg = '#161616'
file_panel_bg = '#161616'
sidebar_bg = '#161616'
footer_bg = '#161616'
modal_bg = '#161616'

# ========= Foreground (fg) =========
full_screen_fg = '#f2f4f8'
file_panel_fg = '#f2f4f8'
sidebar_fg = '#f2f4f8'
footer_fg = '#f2f4f8'
modal_fg = '#f2f4f8'

# ========= Special Color =========
cursor = '#f2f4f8'
correct = '#42be65'
error = '#ff7eb6'
hint = '#78a9ff'
cancel = '#ee5396'
gradient_color = ['#161616', "#525252"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#161616'
file_panel_top_path = '#525252'
file_panel_item_selected_fg = '#f2f4f8'
file_panel_item_selected_bg = '#262626'

# ========= Sidebar Special Items =========
sidebar_title = '#3ddbd9'
sidebar_item_selected_fg = '#f2f4f8'
sidebar_item_selected_bg = '#262626'
sidebar_divider = '#525252'

# ========= Modal Special Items =========
modal_cancel_fg = "#161616"
modal_cancel_bg = '#ee5396'
modal_confirm_fg = "#161616"
modal_confirm_bg = '#42be65'
